bucket_no_upscale = true
bucket_reso_steps = 64
cache_latents = true
caption_extension = ".txt"
clip_skip = 1
dynamo_backend = "no"
enable_bucket = true
epoch = 10
gradient_accumulation_steps = 1
huber_c = 0.1
huber_schedule = "snr"
learning_rate = 0.0002
logging_dir = "/mnt/storage/ai_training/tensorboard/logs"
loss_type = "l2"
lr_scheduler = "cosine"
lr_scheduler_args = []
lr_scheduler_num_cycles = 1
lr_scheduler_power = 1
lr_warmup_steps = 160
max_bucket_reso = 2048
max_data_loader_n_workers = 0
max_grad_norm = 1
max_timestep = 1000
max_token_length = 75
max_train_epochs = 10
max_train_steps = 1600
min_bucket_reso = 256
mixed_precision = "fp16"
multires_noise_discount = 0.3
network_alpha = 1
network_args = [ "conv_dim=1", "conv_alpha=1", "module_dropout=0.3",]
network_dim = 8
network_dropout = 0.2
network_module = "networks.lora"
noise_offset_type = "Original"
optimizer_args = []
optimizer_type = "AdamW"
output_dir = "/mnt/storage/ai_training/LoraTraining-DatasetPrep/output/paisley"
output_name = "paisley_v2"
pretrained_model_name_or_path = "/mnt/storage/ai_training/models/deliberate_v2.safetensors"
prior_loss_weight = 1
resolution = "512,512"
sample_prompts = "/mnt/storage/ai_training/LoraTraining-DatasetPrep/output/paisley/prompt.txt"
sample_sampler = "euler_a"
save_every_n_epochs = 1
save_model_as = "safetensors"
save_precision = "fp16"
scale_weight_norms = 1
text_encoder_lr = 0.0001
train_batch_size = 12
train_data_dir = "/mnt/storage/ai_training/LoraTraining-DatasetPrep/dataset"
unet_lr = 0.0001
xformers = true
